[package]
name = "shalom_codegen"
version = "0.1.0"
edition = "2021"

[lib]
name = "shalom_codegen"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.86"
apollo-compiler = "=1.0.0-beta.20"
minijinja = "2.1.1"
