repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/crate-ci/typos
      rev: v1.31.1
      hooks:
          - id: typos

    - repo: local
      hooks:
          - id: format-dart
            name: Format dart
            entry: dart format --set-exit-if-changed
            
            language: dart
            files: \.dart$
            types: [file]
