repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/crate-ci/typos
      rev: v1.31.1
      hooks:
          - id: typos

    - repo: local
      hooks:
          - id: flutter-format
            name: Run dart format
            entry: dart format --line-length 100
            language: system
            pass_filenames: true
            types: [dart]
