# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  DART_BIN:
    sh: |
      if command -v fvm &> /dev/null; then
        echo "fvm dart"
      else
        echo "dart"
      fi

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  fmt:
    cmds:
      - cd rust && cargo fmt
      - cd rust/shalom_dart_codegen/dart_tests && {{.DART_BIN}} format ./test ./lib
      - '{{.DART_BIN}} format ./dart'

  fix:
    cmds:
      - cd rust && cargo fmt
      - cd rust && cargo clippy --fix --allow-dirty

  lint:
    cmds:
      - cd rust && cargo fmt -- --check
      - cd rust && cargo clippy -- -D warnings
      - cd rust/shalom_dart_codegen/dart_tests && find . -type f -name "*.dart" -not -path "*/__graphql__/*" | xargs {{.DART_BIN}} format --set-exit-if-changed
      - cd rust/shalom_dart_codegen/dart_tests && {{.DART_BIN}} analyze ./test ./lib
      - cd dart/shalom_core && {{.DART_BIN}} analyze ./test ./lib

  test:
    cmds:
      - cd rust && cargo test -- --test-threads=2
      - cd dart/shalom_core && {{.DART_BIN}} test