# https://taskfile.dev

version: "3"

vars:
    GREETING: Hello, World!

tasks:
    default:
        cmds:
            - echo "{{.GREETING}}"
        silent: true
    fmt:
        cmds:
            - cd rust && cargo fmt
            - cd rust/shalom_dart_codegen/dart_tests && dart format ./test ./lib
            - dart format ./dart
    fix:
        cmds:
            - cd rust && cargo fmt
            - cd rust && cargo clippy --fix --allow-dirty
    lint:
        cmds:
            - cd rust && cargo fmt -- --check
            - cd rust && cargo clippy -- -D warnings
            - cd rust/shalom_dart_codegen/dart_tests && find . -type f -name "*.dart" -not -path "*/__graphql__/*" | xargs dart format --set-exit-if-changed
            - cd rust/shalom_dart_codegen/dart_tests && dart analyze ./test ./lib
            - typos
    test:
        cmds:
            # 2 threads, won't kill my pc
            - cd rust && cargo test -- --test-threads=2