mutation InputListEnumRequired($foo: [Gender!]!) {
    inputListEnumRequired(foo: $foo)
}

mutation InputListEnumOptionalWithDefault($foo: [Gender!] = null) {
    inputListEnumOptionalWithDefault(foo: $foo)
}

mutation InputListEnumMaybe($foo: [Gender!]) {
    inputListEnumMaybe(foo: $foo)
}

mutation InputListEnumInsideInputObject($input: ObjectWithListOfInput!) {
    inputListEnumInsideInputObject(input: $input)
}
