[package]
name = "graphql_dart_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
minijinja = "1.0"
graphql-parser = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
