query SubscribeToAllFields {
    user {
        id    
        name 
        email
        age
    }
}

query SubscribeToSomeFields {
    user {
        id
        name
    }
}

query SubscribeToAllNestedFields {
   userInfo {
       id
       user {
           id 
           name
           email
           age
       } 
       address {
          id
          street
          city
       }
   }  
}

query SubscribeToSomeNestedFields {
   userInfo {
       id 
       user {
           id 
           name
       } 
       address {
          id
          city
       }
   }  
}