// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_config`, `parse_graphql_response`, `parse_optional_json`, `parse_variables`, `response_to_json`

Future<RuntimeHandle> initRuntime({
  required String schemaSdl,
  required List<String> fragmentSdls,
  String? configJson,
}) => RustLib.instance.api.crateApiRuntimeInitRuntime(
  schemaSdl: schemaSdl,
  fragmentSdls: fragmentSdls,
  configJson: configJson,
);

Stream<String> listenRequests({required RuntimeHandle handle}) =>
    RustLib.instance.api.crateApiRuntimeListenRequests(handle: handle);

Future<String> request({
  required RuntimeHandle handle,
  required String query,
  String? variablesJson,
}) => RustLib.instance.api.crateApiRuntimeRequest(
  handle: handle,
  query: query,
  variablesJson: variablesJson,
);

Future<void> pushResponse({
  required RuntimeHandle handle,
  required BigInt requestId,
  required String responseJson,
}) => RustLib.instance.api.crateApiRuntimePushResponse(
  handle: handle,
  requestId: requestId,
  responseJson: responseJson,
);

Future<void> pushTransportError({
  required RuntimeHandle handle,
  required BigInt requestId,
  required String message,
  required String code,
  String? detailsJson,
}) => RustLib.instance.api.crateApiRuntimePushTransportError(
  handle: handle,
  requestId: requestId,
  message: message,
  code: code,
  detailsJson: detailsJson,
);

Future<BigInt> subscribe({
  required RuntimeHandle handle,
  required String targetId,
  String? rootRef,
  required List<String> refs,
}) => RustLib.instance.api.crateApiRuntimeSubscribe(
  handle: handle,
  targetId: targetId,
  rootRef: rootRef,
  refs: refs,
);

Stream<String> listenUpdates({
  required RuntimeHandle handle,
  required BigInt subscriptionId,
}) => RustLib.instance.api.crateApiRuntimeListenUpdates(
  handle: handle,
  subscriptionId: subscriptionId,
);

Future<void> unsubscribe({
  required RuntimeHandle handle,
  required BigInt subscriptionId,
}) => RustLib.instance.api.crateApiRuntimeUnsubscribe(
  handle: handle,
  subscriptionId: subscriptionId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeHandle>>
abstract class RuntimeHandle implements RustOpaqueInterface {}
