// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            Future<RuntimeHandle>  initRuntime({required String schemaSdl , required List<String> fragmentSdls , required RuntimeConfig config }) => RustLib.instance.api.crateApiRuntimeInitRuntime(schemaSdl: schemaSdl, fragmentSdls: fragmentSdls, config: config);

Future<UnboundedReceiverStreamRequestEnvelope?>  takeRequestStream({required RuntimeHandle handle }) => RustLib.instance.api.crateApiRuntimeTakeRequestStream(handle: handle);

Future<RuntimeResponse>  request({required RuntimeHandle handle , required String query , MapStringValue? variables }) => RustLib.instance.api.crateApiRuntimeRequest(handle: handle, query: query, variables: variables);

Future<void>  pushResponse({required RuntimeHandle handle , required BigInt requestId , required GraphQlResponse response }) => RustLib.instance.api.crateApiRuntimePushResponse(handle: handle, requestId: requestId, response: response);

Future<BigInt>  subscribe({required RuntimeHandle handle , required String operationId , required List<String> refs }) => RustLib.instance.api.crateApiRuntimeSubscribe(handle: handle, operationId: operationId, refs: refs);

Future<List<RuntimeResponse>>  drainUpdates({required RuntimeHandle handle , required BigInt subscriptionId }) => RustLib.instance.api.crateApiRuntimeDrainUpdates(handle: handle, subscriptionId: subscriptionId);

Future<void>  unsubscribe({required RuntimeHandle handle , required BigInt subscriptionId }) => RustLib.instance.api.crateApiRuntimeUnsubscribe(handle: handle, subscriptionId: subscriptionId);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GraphQLResponse>>
                abstract class GraphQlResponse implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Map < String , Value >>>
                abstract class MapStringValue implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeConfig>>
                abstract class RuntimeConfig implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeHandle>>
                abstract class RuntimeHandle implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeResponse>>
                abstract class RuntimeResponse implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UnboundedReceiverStream < RequestEnvelope >>>
                abstract class UnboundedReceiverStreamRequestEnvelope implements RustOpaqueInterface {
                    

                    
                }
                
            