mutation InputCustomScalarListRequiredMutation($requiredItems: [Point!]!) {
    InputCustomScalarListRequired(requiredItems: $requiredItems) {
        success
        message
    }
}

mutation InputCustomScalarListMaybeMutation($optionalItems: [Point!]) {
    InputCustomScalarListMaybe(optionalItems: $optionalItems) {
        success
        message
    }
}

mutation InputCustomScalarListNullableMaybeMutation($sparseData: [Point]) {
    InputCustomScalarListNullableMaybe(sparseData: $sparseData) {
        success
        message
    }
}

mutation InputCustomScalarListOptionalWithDefaultMutation($defaultItems: [Point!] = null) {
    InputCustomScalarListOptionalWithDefault(defaultItems: $defaultItems) {
        success
        message
    }
}

mutation InputCustomScalarListInsideInputObjectMutation($newContainer: ItemContainerInput!) {
    InputCustomScalarListInsideInputObject(newContainer: $newContainer) {
        success
        message
    }
}
