[package]
name = "shalom_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace = true}
apollo-compiler = "=1.0.0-beta.20"
simple_logger = {workspace = true}
log = {workspace = true}

