// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'json.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `into_object`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`, `from`, `from`

@freezed
sealed class ShalomJsonValue with _$ShalomJsonValue {
  const ShalomJsonValue._();

  const factory ShalomJsonValue.null_() = ShalomJsonValue_Null;
  const factory ShalomJsonValue.boolean(bool field0) = ShalomJsonValue_Boolean;
  const factory ShalomJsonValue.integer(PlatformInt64 field0) =
      ShalomJsonValue_Integer;
  const factory ShalomJsonValue.float(double field0) = ShalomJsonValue_Float;
  const factory ShalomJsonValue.string(String field0) = ShalomJsonValue_String;
  const factory ShalomJsonValue.array(List<ShalomJsonValue> field0) =
      ShalomJsonValue_Array;
  const factory ShalomJsonValue.object(Map<String, ShalomJsonValue> field0) =
      ShalomJsonValue_Object;
}
