// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `cache_value_to_json`, `parse_graphql_response`, `parse_optional_json`, `parse_variables`, `response_to_json`, `to_link_op_type`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`


            /// Set the global log level filter for all Rust-side logging.
void  setLogLevel({required LogLevel level }) => RustLib.instance.api.crateApiRuntimeSetLogLevel(level: level);

/// Initialise the runtime with the schema SDL.
/// Fragment and operation SDLs are registered separately via
/// `register_operation` / `register_fragment` after init.
RuntimeHandle  initRuntime({required String schemaSdl , RuntimeConfigInput? config }) => RustLib.instance.api.crateApiRuntimeInitRuntime(schemaSdl: schemaSdl, config: config);

/// Pre-register a query/mutation SDL so it can be executed by name via `request`.
void  registerOperation({required RuntimeHandle handle , required String document }) => RustLib.instance.api.crateApiRuntimeRegisterOperation(handle: handle, document: document);

/// Pre-register a fragment SDL so it can be subscribed to via `observe_fragment`.
void  registerFragment({required RuntimeHandle handle , required String document }) => RustLib.instance.api.crateApiRuntimeRegisterFragment(handle: handle, document: document);

/// Replace the GraphQL schema with a new SDL string.
///
/// Clears all registered operations/fragments and invalidates the cache.
/// Call this before `registerShalomDefinitions` on hot-reload when the schema
/// file has changed.
void  reloadSchema({required RuntimeHandle handle , required String schemaSdl }) => RustLib.instance.api.crateApiRuntimeReloadSchema(handle: handle, schemaSdl: schemaSdl);

/// Trigger a network request for a pre-registered operation and open a cache
/// subscription. Returns the subscription ID to pass to `listen_subscription`.
///
/// The network request is dispatched through the host link: Dart receives it
/// via `listen_requests`, executes it, and sends the result back via
/// `push_response` / `complete_transport`. Normalization triggers the
/// subscription automatically.
Future<BigInt>  request({required RuntimeHandle handle , required String name , String? variablesJson , required ExecutionPolicyInput executionPolicy }) => RustLib.instance.api.crateApiRuntimeRequest(handle: handle, name: name, variablesJson: variablesJson, executionPolicy: executionPolicy);

/// Write `data_json` to the cache as an optimistic response for the mutation
/// named `op_name`.  Returns an opaque write ID.  Pass this to
/// `rollback_optimistic` to undo the write.
Future<BigInt>  writeOptimistic({required RuntimeHandle handle , required String opName , required String dataJson }) => RustLib.instance.api.crateApiRuntimeWriteOptimistic(handle: handle, opName: opName, dataJson: dataJson);

/// Undo a previous `write_optimistic` call.  No-op if the ID is not found.
void  rollbackOptimistic({required RuntimeHandle handle , required BigInt writeId }) => RustLib.instance.api.crateApiRuntimeRollbackOptimistic(handle: handle, writeId: writeId);

/// Open a cache subscription for a pre-registered fragment at the given anchor.
/// Returns the subscription ID to pass to `listen_subscription`.
///
/// Emits the current cached value immediately if available.
BigInt  observeFragment({required RuntimeHandle handle , required ObservedRefInput refInput }) => RustLib.instance.api.crateApiRuntimeObserveFragment(handle: handle, refInput: refInput);

/// Rebind an existing fragment subscription to a new `ObservedRefInput`.
///
/// - Same `observable_id`: fast anchor swap, same subscription ID returned.
/// - Different `observable_id`: full teardown + new subscription, new ID returned.
BigInt  rebindSubscription({required RuntimeHandle handle , required BigInt subscriptionId , required ObservedRefInput newRef }) => RustLib.instance.api.crateApiRuntimeRebindSubscription(handle: handle, subscriptionId: subscriptionId, newRef: newRef);

void  unsubscribe({required RuntimeHandle handle , required BigInt subscriptionId }) => RustLib.instance.api.crateApiRuntimeUnsubscribe(handle: handle, subscriptionId: subscriptionId);

/// Stream cache-update notifications for an existing subscription.
///
/// Errors from the cache (GraphQL errors, transport errors) are encoded as
/// `{"__error__": "<message>"}` so Dart can route them to `addError` without
/// relying on FRB's unhandled-future propagation path.
Stream<String>  listenSubscription({required RuntimeHandle handle , required BigInt subscriptionId }) => RustLib.instance.api.crateApiRuntimeListenSubscription(handle: handle, subscriptionId: subscriptionId);

/// Stream of serialised request envelopes that Dart must execute and respond to.
Stream<String>  listenRequests({required RuntimeHandle handle }) => RustLib.instance.api.crateApiRuntimeListenRequests(handle: handle);

Future<void>  pushResponse({required RuntimeHandle handle , required BigInt requestId , required String responseJson }) => RustLib.instance.api.crateApiRuntimePushResponse(handle: handle, requestId: requestId, responseJson: responseJson);

Future<void>  pushTransportError({required RuntimeHandle handle , required BigInt requestId , required String message , required String code , String? detailsJson }) => RustLib.instance.api.crateApiRuntimePushTransportError(handle: handle, requestId: requestId, message: message, code: code, detailsJson: detailsJson);

/// Signal that all responses for `request_id` have been delivered.
Future<void>  completeTransport({required RuntimeHandle handle , required BigInt requestId }) => RustLib.instance.api.crateApiRuntimeCompleteTransport(handle: handle, requestId: requestId);

/// Returns a JSON object mapping each cache key to its active subscriber count.
///
/// Example: `{"ROOT_QUERY": 2, "User:1": 1}`
String  getSubscriptionCounts({required RuntimeHandle handle }) => RustLib.instance.api.crateApiRuntimeGetSubscriptionCounts(handle: handle);

/// Returns info about every active subscription currently watching [key].
List<SubscriberInfo>  getKeySubscribers({required RuntimeHandle handle , required String key }) => RustLib.instance.api.crateApiRuntimeGetKeySubscribers(handle: handle, key: key);

/// Returns all keys currently stored in the normalized cache.
List<String>  getCacheKeys({required RuntimeHandle handle }) => RustLib.instance.api.crateApiRuntimeGetCacheKeys(handle: handle);

/// Returns a pretty-printed JSON string for the cache entry at [key],
/// or `None` if the key is not present.
///
/// `CacheValue::Ref` entries are serialised as `{"__ref": "<key>"}`.
String?  getCacheEntry({required RuntimeHandle handle , required String key }) => RustLib.instance.api.crateApiRuntimeGetCacheEntry(handle: handle, key: key);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeHandle>>
                abstract class RuntimeHandle implements RustOpaqueInterface {
                    

                    
                }
                

enum ExecutionPolicyInput {
                    networkFirst,
cacheFirst,
                    ;
                    
                }

enum LogLevel {
                    error,
warn,
info,
debug,
trace,
                    ;
                    
                }

/// Dart-facing representation of an observed fragment reference.
///
/// `observable_id` is the fragment name; `anchor` is the cache key (e.g. `"User:1"`).
class ObservedRefInput  {
                final String observableId;
final String anchor;

                const ObservedRefInput({required this.observableId ,required this.anchor ,});

                
                

                
        @override
        int get hashCode => observableId.hashCode^anchor.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is ObservedRefInput &&
                runtimeType == other.runtimeType
                && observableId == other.observableId&& anchor == other.anchor;
        
            }

/// Dart-facing runtime configuration.  Empty for now; fields will be added as
/// the runtime gains configurable behaviour (e.g. GC tuning, cache limits).
class RuntimeConfigInput  {
                

                const RuntimeConfigInput();

                
                

                
        @override
        int get hashCode => 0;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is RuntimeConfigInput &&
                runtimeType == other.runtimeType
                ;
        
            }

/// Info about a single subscription watching a cache key.
class SubscriberInfo  {
                final BigInt id;
/// `"operation"` or `"fragment"`
final String kind;
final String name;
/// For fragment subscriptions: the anchor cache key.
final String? anchor;
/// Serialised JSON of subscription variables, if any.
final String? variablesJson;
/// All cache keys this subscription is currently watching.
final List<String> watchedKeys;

                const SubscriberInfo({required this.id ,required this.kind ,required this.name ,this.anchor ,this.variablesJson ,required this.watchedKeys ,});

                
                

                
        @override
        int get hashCode => id.hashCode^kind.hashCode^name.hashCode^anchor.hashCode^variablesJson.hashCode^watchedKeys.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SubscriberInfo &&
                runtimeType == other.runtimeType
                && id == other.id&& kind == other.kind&& name == other.name&& anchor == other.anchor&& variablesJson == other.variablesJson&& watchedKeys == other.watchedKeys;
        
            }
            