// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_config`, `parse_graphql_response`, `parse_optional_json`, `parse_variables`, `response_to_json`, `to_link_op_type`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Initialise the runtime with the schema SDL.
/// Fragment and operation SDLs are registered separately via
/// `register_operation` / `register_fragment` after init.
Future<RuntimeHandle> initRuntime({
  required String schemaSdl,
  String? configJson,
}) => RustLib.instance.api.crateApiRuntimeInitRuntime(
  schemaSdl: schemaSdl,
  configJson: configJson,
);

/// Pre-register a query/mutation SDL so it can be executed by name via `request`.
Future<void> registerOperation({
  required RuntimeHandle handle,
  required String document,
}) => RustLib.instance.api.crateApiRuntimeRegisterOperation(
  handle: handle,
  document: document,
);

/// Pre-register a fragment SDL so it can be subscribed to via `observe_fragment`.
Future<void> registerFragment({
  required RuntimeHandle handle,
  required String document,
}) => RustLib.instance.api.crateApiRuntimeRegisterFragment(
  handle: handle,
  document: document,
);

/// Trigger a network request for a pre-registered operation and open a cache
/// subscription. Returns the subscription ID to pass to `listen_subscription`.
///
/// The network request is dispatched through the host link: Dart receives it
/// via `listen_requests`, executes it, and sends the result back via
/// `push_response` / `complete_transport`. Normalization triggers the
/// subscription automatically.
Future<BigInt> request({
  required RuntimeHandle handle,
  required String name,
  String? variablesJson,
}) => RustLib.instance.api.crateApiRuntimeRequest(
  handle: handle,
  name: name,
  variablesJson: variablesJson,
);

/// Open a cache subscription for a pre-registered fragment at the given anchor.
/// Returns the subscription ID to pass to `listen_subscription`.
///
/// Emits the current cached value immediately if available.
BigInt observeFragment({
  required RuntimeHandle handle,
  required ObservedRefInput refInput,
}) => RustLib.instance.api.crateApiRuntimeObserveFragment(
  handle: handle,
  refInput: refInput,
);

/// Rebind an existing fragment subscription to a new `ObservedRefInput`.
///
/// - Same `observable_id`: fast anchor swap, same subscription ID returned.
/// - Different `observable_id`: full teardown + new subscription, new ID returned.
BigInt rebindSubscription({
  required RuntimeHandle handle,
  required BigInt subscriptionId,
  required ObservedRefInput newRef,
}) => RustLib.instance.api.crateApiRuntimeRebindSubscription(
  handle: handle,
  subscriptionId: subscriptionId,
  newRef: newRef,
);

void unsubscribe({
  required RuntimeHandle handle,
  required BigInt subscriptionId,
}) => RustLib.instance.api.crateApiRuntimeUnsubscribe(
  handle: handle,
  subscriptionId: subscriptionId,
);

/// Stream cache-update notifications for an existing subscription.
Stream<String> listenSubscription({
  required RuntimeHandle handle,
  required BigInt subscriptionId,
}) => RustLib.instance.api.crateApiRuntimeListenSubscription(
  handle: handle,
  subscriptionId: subscriptionId,
);

/// Stream of serialised request envelopes that Dart must execute and respond to.
Stream<String> listenRequests({required RuntimeHandle handle}) =>
    RustLib.instance.api.crateApiRuntimeListenRequests(handle: handle);

Future<void> pushResponse({
  required RuntimeHandle handle,
  required BigInt requestId,
  required String responseJson,
}) => RustLib.instance.api.crateApiRuntimePushResponse(
  handle: handle,
  requestId: requestId,
  responseJson: responseJson,
);

Future<void> pushTransportError({
  required RuntimeHandle handle,
  required BigInt requestId,
  required String message,
  required String code,
  String? detailsJson,
}) => RustLib.instance.api.crateApiRuntimePushTransportError(
  handle: handle,
  requestId: requestId,
  message: message,
  code: code,
  detailsJson: detailsJson,
);

/// Signal that all responses for `request_id` have been delivered.
Future<void> completeTransport({
  required RuntimeHandle handle,
  required BigInt requestId,
}) => RustLib.instance.api.crateApiRuntimeCompleteTransport(
  handle: handle,
  requestId: requestId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RuntimeHandle>>
abstract class RuntimeHandle implements RustOpaqueInterface {}

/// Dart-facing representation of an observed fragment reference.
///
/// `observable_id` is the fragment name; `anchor` is the cache key (e.g. `"User:1"`).
class ObservedRefInput {
  final String observableId;
  final String anchor;

  const ObservedRefInput({required this.observableId, required this.anchor});

  @override
  int get hashCode => observableId.hashCode ^ anchor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ObservedRefInput &&
          runtimeType == other.runtimeType &&
          observableId == other.observableId &&
          anchor == other.anchor;
}
