// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'json.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'ws.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_ws_event`, `graphql_response_to_json`

/// Create a new sans-IO state machine.
///
/// `connection_params_json` — optional JSON object forwarded as the
/// `connection_init` payload (e.g. `{"Authorization":"Bearer …"}`).
WsSansIo createWsSansIo({ShalomJsonValue? connectionParams}) => RustLib
    .instance
    .api
    .crateApiWsCreateWsSansIo(connectionParams: connectionParams);

/// The `connection_init` frame to send immediately after the socket opens.
String wsConnectionInitFrame({required WsSansIo sansio}) =>
    RustLib.instance.api.crateApiWsWsConnectionInitFrame(sansio: sansio);

/// Build a `subscribe` frame for a new operation and register it internally.
///
/// `variables_json` — optional JSON object of operation variables.
String wsSubscribeFrame({
  required WsSansIo sansio,
  required String opId,
  required String query,
  ShalomJsonValue? variables,
  String? operationName,
}) => RustLib.instance.api.crateApiWsWsSubscribeFrame(
  sansio: sansio,
  opId: opId,
  query: query,
  variables: variables,
  operationName: operationName,
);

/// Build a `complete` frame to cancel an in-flight operation.
String wsCompleteFrame({required WsSansIo sansio, required String opId}) =>
    RustLib.instance.api.crateApiWsWsCompleteFrame(sansio: sansio, opId: opId);

/// Build a `pong` frame in response to a server `ping`.
///
/// `payload_json` — the payload from the `PingReceived` event, if any.
String wsPongFrame({required WsSansIo sansio, ShalomJsonValue? payload}) =>
    RustLib.instance.api.crateApiWsWsPongFrame(
      sansio: sansio,
      payload: payload,
    );

/// Build a `ping` frame to send to the server.
String wsPingFrame() => RustLib.instance.api.crateApiWsWsPingFrame();

/// Process a raw text frame received from the server.
///
/// Returns a list of typed events for Dart to dispatch on.
/// On a protocol error returns `Err` — caller should close the socket.
List<WsLinkEvent> wsOnMessage({
  required WsSansIo sansio,
  required String raw,
}) => RustLib.instance.api.crateApiWsWsOnMessage(sansio: sansio, raw: raw);

/// Reset connection state for reconnect. Preserves active operation ids.
void wsReset({required WsSansIo sansio}) =>
    RustLib.instance.api.crateApiWsWsReset(sansio: sansio);

/// Whether the connection has been acknowledged.
bool wsIsConnected({required WsSansIo sansio}) =>
    RustLib.instance.api.crateApiWsWsIsConnected(sansio: sansio);

/// All currently registered operation ids (active + pending-reconnect).
List<String> wsActiveOperationIds({required WsSansIo sansio}) =>
    RustLib.instance.api.crateApiWsWsActiveOperationIds(sansio: sansio);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WsSansIo>>
abstract class WsSansIo implements RustOpaqueInterface {}

@freezed
sealed class WsLinkEvent with _$WsLinkEvent {
  const WsLinkEvent._();

  /// Connection acknowledged — safe to flush pending operations.
  const factory WsLinkEvent.connected() = WsLinkEvent_Connected;

  /// Server sent a Ping.  Send back the frame from `ws_pong_frame()`.
  const factory WsLinkEvent.pingReceived({ShalomJsonValue? payload}) =
      WsLinkEvent_PingReceived;

  /// Server sent a Pong — typically in response to a caller-initiated
  /// heartbeat `ws_ping_frame()`. Caller should cancel any pending
  /// pong-timeout timer.
  const factory WsLinkEvent.pongReceived({ShalomJsonValue? payload}) =
      WsLinkEvent_PongReceived;

  /// A data / error payload arrived for `op_id`.
  /// `response_json` is the complete GraphQL response payload. Dart passes
  /// it through untouched to the runtime bridge.
  const factory WsLinkEvent.operationResponse({
    required String opId,
    required String responseJson,
  }) = WsLinkEvent_OperationResponse;

  /// The server has finished sending data for `op_id`.
  const factory WsLinkEvent.operationComplete({required String opId}) =
      WsLinkEvent_OperationComplete;

  /// Protocol violation — close the WebSocket with `code`.
  const factory WsLinkEvent.protocolError({
    required int code,
    required String reason,
  }) = WsLinkEvent_ProtocolError;
}
