
query GetStringList {
    stringList
}

query GetStringListOptional {
    stringListOptional
}

query GetStringListWithNulls {
    stringListWithNulls
}

query GetStringListFullyOptional {
    stringListFullyOptional
}


query GetIntList {
    intList
}

query GetIntListOptional {
    intListOptional
}


query GetFloatList {
    floatList
}

query GetFloatListWithNulls {
    floatListWithNulls
}


query GetBooleanList {
    booleanList
}


query GetIDList {
    idList
}


mutation UpdateStringList($strings: [String!]!) {
    updateStringList(strings: $strings) {
        success
    }
}

mutation UpdateIntList($ints: [Int]) {
    updateIntList(ints: $ints) {
        success
    }
}

mutation UpdateFloatList($floats: [Float!]!) {
    updateFloatList(floats: $floats) {
        success
    }
}

mutation UpdateBooleanList($booleans: [Boolean!]!) {
    updateBooleanList(booleans: $booleans) {
        success
    }
}

mutation UpdateIDList($ids: [ID!]!) {
    updateIDList(ids: $ids) {
        success
    }
}


mutation CreateUser($user: UserInput!) {
    createUser(user: $user) {
        success
    }
}