
mutation InputScalarListRequired($strings: [String!]!) {
    InputScalarListRequired(strings: $strings) {
        success
    }
}

mutation InputScalarListMaybe($ints: [Int]) {
    InputScalarListMaybe(ints: $ints) {
        success
    }
}
mutation InputScalarListOptional($names: [String] = null) {
    InputScalarListOptional(names: $names) {
        success
    }
}

mutation InputScalarInsideInputType($user: UserInput!) {
    InputScalarInsideInputType(user: $user) {
        success
    }
}

