
mutation InputScalarListRequired($strings: [String!]!) {
    InputScalarListRequired(strings: $strings) {
        success
    }
}

mutation InputScalarListMaybe($ints: [Int]) {
    InputScalarListMaybe(ints: $ints) {
        success
    }
}

mutation InputScalarInsideInputType($user: UserInput!) {
    InputScalarInsideInputType(user: $user) {
        success
    }
}

mutation InputScalarListOptional($name: String) {
    InputScalarListOptional(name: $name) {
        success
    }
}