
mutation InputScalarListRequiredMutation($strings: [String!]!) {
    InputScalarListRequired(strings: $strings) {
        success
    }
}

mutation InputScalarListMaybeMutation($ints: [Int]) {
    InputScalarListMaybe(ints: $ints) {
        success
    }
}
mutation InputScalarListOptionalMutation($names: [String] = null) {
    InputScalarListOptional(names: $names) {
        success
    }
}

mutation InputScalarInsideInputTypeMutation($user: UserInput!) {
    InputScalarInsideInputType(user: $user) {
        success
    }
}
