// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/runtime.dart';
import 'api/ws.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiRuntimeInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -449710794;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'shalom_ffi',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiRuntimeCompleteTransport({
    required RuntimeHandle handle,
    required BigInt requestId,
  });

  WsSansIo crateApiWsCreateWsSansIo({String? connectionParamsJson});

  Future<void> crateApiRuntimeInitApp();

  Future<RuntimeHandle> crateApiRuntimeInitRuntime({
    required String schemaSdl,
    String? configJson,
  });

  Stream<String> crateApiRuntimeListenRequests({required RuntimeHandle handle});

  Stream<String> crateApiRuntimeListenSubscription({
    required RuntimeHandle handle,
    required BigInt subscriptionId,
  });

  BigInt crateApiRuntimeObserveFragment({
    required RuntimeHandle handle,
    required ObservedRefInput refInput,
  });

  Future<void> crateApiRuntimePushResponse({
    required RuntimeHandle handle,
    required BigInt requestId,
    required String responseJson,
  });

  Future<void> crateApiRuntimePushTransportError({
    required RuntimeHandle handle,
    required BigInt requestId,
    required String message,
    required String code,
    String? detailsJson,
  });

  BigInt crateApiRuntimeRebindSubscription({
    required RuntimeHandle handle,
    required BigInt subscriptionId,
    required ObservedRefInput newRef,
  });

  Future<void> crateApiRuntimeRegisterFragment({
    required RuntimeHandle handle,
    required String document,
  });

  Future<void> crateApiRuntimeRegisterOperation({
    required RuntimeHandle handle,
    required String document,
  });

  Future<BigInt> crateApiRuntimeRequest({
    required RuntimeHandle handle,
    required String name,
    String? variablesJson,
  });

  void crateApiRuntimeUnsubscribe({
    required RuntimeHandle handle,
    required BigInt subscriptionId,
  });

  List<String> crateApiWsWsActiveOperationIds({required WsSansIo sansio});

  String crateApiWsWsCompleteFrame({
    required WsSansIo sansio,
    required String opId,
  });

  String crateApiWsWsConnectionInitFrame({required WsSansIo sansio});

  bool crateApiWsWsIsConnected({required WsSansIo sansio});

  List<WsLinkEvent> crateApiWsWsOnMessage({
    required WsSansIo sansio,
    required String raw,
  });

  String crateApiWsWsPingFrame();

  String crateApiWsWsPongFrame({required WsSansIo sansio, String? payloadJson});

  void crateApiWsWsReset({required WsSansIo sansio});

  String crateApiWsWsSubscribeFrame({
    required WsSansIo sansio,
    required String opId,
    required String query,
    String? variablesJson,
    String? operationName,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RuntimeHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RuntimeHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RuntimeHandlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WsSansIo;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WsSansIo;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WsSansIoPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiRuntimeCompleteTransport({
    required RuntimeHandle handle,
    required BigInt requestId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_u_64(requestId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRuntimeCompleteTransportConstMeta,
        argValues: [handle, requestId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeCompleteTransportConstMeta =>
      const TaskConstMeta(
        debugName: "complete_transport",
        argNames: ["handle", "requestId"],
      );

  @override
  WsSansIo crateApiWsCreateWsSansIo({String? connectionParamsJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(connectionParamsJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWsCreateWsSansIoConstMeta,
        argValues: [connectionParamsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsCreateWsSansIoConstMeta => const TaskConstMeta(
    debugName: "create_ws_sans_io",
    argNames: ["connectionParamsJson"],
  );

  @override
  Future<void> crateApiRuntimeInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRuntimeInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<RuntimeHandle> crateApiRuntimeInitRuntime({
    required String schemaSdl,
    String? configJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(schemaSdl, serializer);
          sse_encode_opt_String(configJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRuntimeInitRuntimeConstMeta,
        argValues: [schemaSdl, configJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeInitRuntimeConstMeta => const TaskConstMeta(
    debugName: "init_runtime",
    argNames: ["schemaSdl", "configJson"],
  );

  @override
  Stream<String> crateApiRuntimeListenRequests({
    required RuntimeHandle handle,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
              handle,
              serializer,
            );
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiRuntimeListenRequestsConstMeta,
          argValues: [handle, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRuntimeListenRequestsConstMeta =>
      const TaskConstMeta(
        debugName: "listen_requests",
        argNames: ["handle", "sink"],
      );

  @override
  Stream<String> crateApiRuntimeListenSubscription({
    required RuntimeHandle handle,
    required BigInt subscriptionId,
  }) {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
              handle,
              serializer,
            );
            sse_encode_u_64(subscriptionId, serializer);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiRuntimeListenSubscriptionConstMeta,
          argValues: [handle, subscriptionId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiRuntimeListenSubscriptionConstMeta =>
      const TaskConstMeta(
        debugName: "listen_subscription",
        argNames: ["handle", "subscriptionId", "sink"],
      );

  @override
  BigInt crateApiRuntimeObserveFragment({
    required RuntimeHandle handle,
    required ObservedRefInput refInput,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_box_autoadd_observed_ref_input(refInput, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRuntimeObserveFragmentConstMeta,
        argValues: [handle, refInput],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeObserveFragmentConstMeta =>
      const TaskConstMeta(
        debugName: "observe_fragment",
        argNames: ["handle", "refInput"],
      );

  @override
  Future<void> crateApiRuntimePushResponse({
    required RuntimeHandle handle,
    required BigInt requestId,
    required String responseJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_u_64(requestId, serializer);
          sse_encode_String(responseJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRuntimePushResponseConstMeta,
        argValues: [handle, requestId, responseJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimePushResponseConstMeta =>
      const TaskConstMeta(
        debugName: "push_response",
        argNames: ["handle", "requestId", "responseJson"],
      );

  @override
  Future<void> crateApiRuntimePushTransportError({
    required RuntimeHandle handle,
    required BigInt requestId,
    required String message,
    required String code,
    String? detailsJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_u_64(requestId, serializer);
          sse_encode_String(message, serializer);
          sse_encode_String(code, serializer);
          sse_encode_opt_String(detailsJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRuntimePushTransportErrorConstMeta,
        argValues: [handle, requestId, message, code, detailsJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimePushTransportErrorConstMeta =>
      const TaskConstMeta(
        debugName: "push_transport_error",
        argNames: ["handle", "requestId", "message", "code", "detailsJson"],
      );

  @override
  BigInt crateApiRuntimeRebindSubscription({
    required RuntimeHandle handle,
    required BigInt subscriptionId,
    required ObservedRefInput newRef,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_u_64(subscriptionId, serializer);
          sse_encode_box_autoadd_observed_ref_input(newRef, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRuntimeRebindSubscriptionConstMeta,
        argValues: [handle, subscriptionId, newRef],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeRebindSubscriptionConstMeta =>
      const TaskConstMeta(
        debugName: "rebind_subscription",
        argNames: ["handle", "subscriptionId", "newRef"],
      );

  @override
  Future<void> crateApiRuntimeRegisterFragment({
    required RuntimeHandle handle,
    required String document,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_String(document, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRuntimeRegisterFragmentConstMeta,
        argValues: [handle, document],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeRegisterFragmentConstMeta =>
      const TaskConstMeta(
        debugName: "register_fragment",
        argNames: ["handle", "document"],
      );

  @override
  Future<void> crateApiRuntimeRegisterOperation({
    required RuntimeHandle handle,
    required String document,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_String(document, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRuntimeRegisterOperationConstMeta,
        argValues: [handle, document],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeRegisterOperationConstMeta =>
      const TaskConstMeta(
        debugName: "register_operation",
        argNames: ["handle", "document"],
      );

  @override
  Future<BigInt> crateApiRuntimeRequest({
    required RuntimeHandle handle,
    required String name,
    String? variablesJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_opt_String(variablesJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRuntimeRequestConstMeta,
        argValues: [handle, name, variablesJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeRequestConstMeta => const TaskConstMeta(
    debugName: "request",
    argNames: ["handle", "name", "variablesJson"],
  );

  @override
  void crateApiRuntimeUnsubscribe({
    required RuntimeHandle handle,
    required BigInt subscriptionId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
            handle,
            serializer,
          );
          sse_encode_u_64(subscriptionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRuntimeUnsubscribeConstMeta,
        argValues: [handle, subscriptionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRuntimeUnsubscribeConstMeta => const TaskConstMeta(
    debugName: "unsubscribe",
    argNames: ["handle", "subscriptionId"],
  );

  @override
  List<String> crateApiWsWsActiveOperationIds({required WsSansIo sansio}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
            sansio,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWsWsActiveOperationIdsConstMeta,
        argValues: [sansio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsActiveOperationIdsConstMeta =>
      const TaskConstMeta(
        debugName: "ws_active_operation_ids",
        argNames: ["sansio"],
      );

  @override
  String crateApiWsWsCompleteFrame({
    required WsSansIo sansio,
    required String opId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
            sansio,
            serializer,
          );
          sse_encode_String(opId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWsWsCompleteFrameConstMeta,
        argValues: [sansio, opId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsCompleteFrameConstMeta => const TaskConstMeta(
    debugName: "ws_complete_frame",
    argNames: ["sansio", "opId"],
  );

  @override
  String crateApiWsWsConnectionInitFrame({required WsSansIo sansio}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
            sansio,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWsWsConnectionInitFrameConstMeta,
        argValues: [sansio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsConnectionInitFrameConstMeta =>
      const TaskConstMeta(
        debugName: "ws_connection_init_frame",
        argNames: ["sansio"],
      );

  @override
  bool crateApiWsWsIsConnected({required WsSansIo sansio}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
            sansio,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWsWsIsConnectedConstMeta,
        argValues: [sansio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsIsConnectedConstMeta =>
      const TaskConstMeta(debugName: "ws_is_connected", argNames: ["sansio"]);

  @override
  List<WsLinkEvent> crateApiWsWsOnMessage({
    required WsSansIo sansio,
    required String raw,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
            sansio,
            serializer,
          );
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ws_link_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWsWsOnMessageConstMeta,
        argValues: [sansio, raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsOnMessageConstMeta => const TaskConstMeta(
    debugName: "ws_on_message",
    argNames: ["sansio", "raw"],
  );

  @override
  String crateApiWsWsPingFrame() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWsWsPingFrameConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsPingFrameConstMeta =>
      const TaskConstMeta(debugName: "ws_ping_frame", argNames: []);

  @override
  String crateApiWsWsPongFrame({
    required WsSansIo sansio,
    String? payloadJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
            sansio,
            serializer,
          );
          sse_encode_opt_String(payloadJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWsWsPongFrameConstMeta,
        argValues: [sansio, payloadJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsPongFrameConstMeta => const TaskConstMeta(
    debugName: "ws_pong_frame",
    argNames: ["sansio", "payloadJson"],
  );

  @override
  void crateApiWsWsReset({required WsSansIo sansio}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
            sansio,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWsWsResetConstMeta,
        argValues: [sansio],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsResetConstMeta =>
      const TaskConstMeta(debugName: "ws_reset", argNames: ["sansio"]);

  @override
  String crateApiWsWsSubscribeFrame({
    required WsSansIo sansio,
    required String opId,
    required String query,
    String? variablesJson,
    String? operationName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
            sansio,
            serializer,
          );
          sse_encode_String(opId, serializer);
          sse_encode_String(query, serializer);
          sse_encode_opt_String(variablesJson, serializer);
          sse_encode_opt_String(operationName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWsWsSubscribeFrameConstMeta,
        argValues: [sansio, opId, query, variablesJson, operationName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWsWsSubscribeFrameConstMeta => const TaskConstMeta(
    debugName: "ws_subscribe_frame",
    argNames: ["sansio", "opId", "query", "variablesJson", "operationName"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RuntimeHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RuntimeHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_WsSansIo => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_WsSansIo => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RuntimeHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RuntimeHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WsSansIo
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WsSansIoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WsSansIo
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WsSansIoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RuntimeHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RuntimeHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WsSansIo
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WsSansIoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RuntimeHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RuntimeHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  WsSansIo
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WsSansIoImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ObservedRefInput dco_decode_box_autoadd_observed_ref_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_observed_ref_input(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<WsLinkEvent> dco_decode_list_ws_link_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ws_link_event).toList();
  }

  @protected
  ObservedRefInput dco_decode_observed_ref_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ObservedRefInput(
      observableId: dco_decode_String(arr[0]),
      anchor: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WsLinkEvent dco_decode_ws_link_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return WsLinkEvent_Connected();
      case 1:
        return WsLinkEvent_PingReceived(
          payloadJson: dco_decode_opt_String(raw[1]),
        );
      case 2:
        return WsLinkEvent_OperationResponse(
          opId: dco_decode_String(raw[1]),
          dataJson: dco_decode_opt_String(raw[2]),
          errorsJson: dco_decode_opt_String(raw[3]),
          extensionsJson: dco_decode_opt_String(raw[4]),
        );
      case 3:
        return WsLinkEvent_OperationComplete(opId: dco_decode_String(raw[1]));
      case 4:
        return WsLinkEvent_ProtocolError(
          code: dco_decode_u_16(raw[1]),
          reason: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RuntimeHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RuntimeHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WsSansIo
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WsSansIoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WsSansIo
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WsSansIoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RuntimeHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RuntimeHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WsSansIo
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WsSansIoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RuntimeHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RuntimeHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  WsSansIo
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return WsSansIoImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ObservedRefInput sse_decode_box_autoadd_observed_ref_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_observed_ref_input(deserializer));
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<WsLinkEvent> sse_decode_list_ws_link_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WsLinkEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ws_link_event(deserializer));
    }
    return ans_;
  }

  @protected
  ObservedRefInput sse_decode_observed_ref_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_observableId = sse_decode_String(deserializer);
    var var_anchor = sse_decode_String(deserializer);
    return ObservedRefInput(observableId: var_observableId, anchor: var_anchor);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WsLinkEvent sse_decode_ws_link_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return WsLinkEvent_Connected();
      case 1:
        var var_payloadJson = sse_decode_opt_String(deserializer);
        return WsLinkEvent_PingReceived(payloadJson: var_payloadJson);
      case 2:
        var var_opId = sse_decode_String(deserializer);
        var var_dataJson = sse_decode_opt_String(deserializer);
        var var_errorsJson = sse_decode_opt_String(deserializer);
        var var_extensionsJson = sse_decode_opt_String(deserializer);
        return WsLinkEvent_OperationResponse(
          opId: var_opId,
          dataJson: var_dataJson,
          errorsJson: var_errorsJson,
          extensionsJson: var_extensionsJson,
        );
      case 3:
        var var_opId = sse_decode_String(deserializer);
        return WsLinkEvent_OperationComplete(opId: var_opId);
      case 4:
        var var_code = sse_decode_u_16(deserializer);
        var var_reason = sse_decode_String(deserializer);
        return WsLinkEvent_ProtocolError(code: var_code, reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    RuntimeHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RuntimeHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    WsSansIo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WsSansIoImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    WsSansIo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WsSansIoImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    RuntimeHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RuntimeHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    WsSansIo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WsSansIoImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRuntimeHandle(
    RuntimeHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RuntimeHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWsSansIo(
    WsSansIo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as WsSansIoImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_observed_ref_input(
    ObservedRefInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_observed_ref_input(self, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_ws_link_event(
    List<WsLinkEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ws_link_event(item, serializer);
    }
  }

  @protected
  void sse_encode_observed_ref_input(
    ObservedRefInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.observableId, serializer);
    sse_encode_String(self.anchor, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_ws_link_event(WsLinkEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case WsLinkEvent_Connected():
        sse_encode_i_32(0, serializer);
      case WsLinkEvent_PingReceived(payloadJson: final payloadJson):
        sse_encode_i_32(1, serializer);
        sse_encode_opt_String(payloadJson, serializer);
      case WsLinkEvent_OperationResponse(
        opId: final opId,
        dataJson: final dataJson,
        errorsJson: final errorsJson,
        extensionsJson: final extensionsJson,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(opId, serializer);
        sse_encode_opt_String(dataJson, serializer);
        sse_encode_opt_String(errorsJson, serializer);
        sse_encode_opt_String(extensionsJson, serializer);
      case WsLinkEvent_OperationComplete(opId: final opId):
        sse_encode_i_32(3, serializer);
        sse_encode_String(opId, serializer);
      case WsLinkEvent_ProtocolError(code: final code, reason: final reason):
        sse_encode_i_32(4, serializer);
        sse_encode_u_16(code, serializer);
        sse_encode_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class RuntimeHandleImpl extends RustOpaque implements RuntimeHandle {
  // Not to be used by end users
  RuntimeHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RuntimeHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RuntimeHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RuntimeHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RuntimeHandlePtr,
  );
}

@sealed
class WsSansIoImpl extends RustOpaque implements WsSansIo {
  // Not to be used by end users
  WsSansIoImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  WsSansIoImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_WsSansIo,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_WsSansIo,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_WsSansIoPtr,
  );
}
