import 'dart:convert';
import 'dart:io';

/// Resolves the file path to the compiled `shalom_ffi` native library
/// for standalone Dart CLI scripts and unit tests.
///
/// In Flutter applications, Flutter's build toolchains automatically bundle
/// and resolve the native dynamic library, so this utility is not needed.
///
/// In pure Dart environments (CLI scripts, `dart test`, `dart run`):
/// 1. Checks `.dart_tool/native_assets.yaml` produced by Dart native assets hooks.
/// 2. Checks standard Cargo target directories (`target/debug`, `target/release`, etc.).
String? resolveNativeLibPath() {
  // 1. Try reading the mapping generated by Dart native assets (JIT / dart test / dart run mode)
  final nativeAssetsFile = File('.dart_tool/native_assets.yaml');
  if (nativeAssetsFile.existsSync()) {
    try {
      final content = nativeAssetsFile.readAsStringSync();
      final doc = jsonDecode(content) as Map<String, dynamic>;
      final nativeAssets = doc['native-assets'] as Map<String, dynamic>?;
      if (nativeAssets != null) {
        for (final osEntry in nativeAssets.values) {
          if (osEntry is Map<String, dynamic>) {
            final asset = osEntry['package:shalom/shalom_ffi'];
            if (asset is List && asset.length > 1) {
              final libPath = asset[1] as String;
              if (File(libPath).existsSync()) return libPath;
            }
          }
        }
      }
    } catch (_) {}
  }

  // 2. Fall back to local cargo target directories across workspace hierarchies
  final libName = Platform.isWindows
      ? 'shalom_ffi.dll'
      : Platform.isMacOS
          ? 'libshalom_ffi.dylib'
          : 'libshalom_ffi.so';

  final searchDirs = [
    'target/debug',
    'target/release',
    '../../target/debug',
    '../../target/release',
    '../../../target/debug',
    '../../../target/release',
    '.dart_tool/lib',
  ];

  for (final dir in searchDirs) {
    final candidate = '$dir/$libName';
    if (File(candidate).existsSync()) return candidate;
  }

  return null;
}
